[settings]
base_branch = "main"
exclude = "CHANGELOG\\.md|\\.github/renovate-tracked-deps\\.json"

[checks.links]
config = ".github/config/lychee.toml"
check_all_local = true

[checks.renovate-deps]
exclude_managers = ["github-actions", "github-runners"]
