#!/usr/bin/env bash
#MISE description="Generate super-linter version mapping from the super-linter repo"

set -euo pipefail

if [ -z "${MISE_PROJECT_ROOT:-}" ]; then
	echo "MISE_PROJECT_ROOT environment variable is not set. Exiting."
	exit 1
fi

cd "${MISE_PROJECT_ROOT}"

if [ -z "${SUPER_LINTER_VERSION:-}" ]; then
	echo "SUPER_LINTER_VERSION environment variable is not set. Exiting."
	exit 1
fi

# Extract clean version (strip slim- prefix and @sha256 digest)
VERSION="${SUPER_LINTER_VERSION#slim-}"
VERSION="${VERSION%%@*}"

REPO="super-linter/super-linter"
TAG="${VERSION}"
OUTPUT="super-linter-versions/${VERSION}.toml"

echo "Extracting tool versions for super-linter ${TAG}..."

# Fetch Dockerfile to extract versions from FROM lines
DOCKERFILE=$(gh api "repos/${REPO}/contents/Dockerfile?ref=${TAG}" -q '.content' | base64 -d)

# Extract version from a FROM line like "FROM koalaman/shellcheck:v0.11.0 AS shellcheck"
_from_version() {
	local image="$1"
	echo "$DOCKERFILE" | grep -E "^FROM ${image}:" | sed "s|.*${image}:\(v\{0,1\}\)|\1|; s| .*||; s|-.*||"
}

# Fetch a pip requirements file and extract the pinned version
_pip_version() {
	local pkg="$1"
	gh api "repos/${REPO}/contents/dependencies/python/${pkg}.txt?ref=${TAG}" -q '.content' | base64 -d | sed "s/${pkg}==//"
}

# Fetch package-lock.json once and extract npm package versions
_PACKAGE_LOCK=""
_npm_version() {
	local pkg="$1"
	if [ -z "$_PACKAGE_LOCK" ]; then
		_PACKAGE_LOCK=$(gh api "repos/${REPO}/contents/dependencies/package-lock.json?ref=${TAG}" -q '.content' | base64 -d)
	fi
	echo "$_PACKAGE_LOCK" |
		python3 -c "import json,sys; print(json.load(sys.stdin)['packages']['node_modules/${pkg}']['version'])"
}

# Collect versions
shellcheck=$(_from_version "koalaman/shellcheck")
shfmt=$(_from_version "mvdan/shfmt")
actionlint=$(_from_version "rhysd/actionlint")
hadolint=$(_from_version "hadolint/hadolint")
editorconfig_checker=$(_from_version "mstruebing/editorconfig-checker")
golangci_lint=$(_from_version "golangci/golangci-lint")
markdownlint=$(_npm_version "markdownlint-cli")
prettier=$(_npm_version "prettier")
biome=$(_npm_version "@biomejs/biome")
ruff=$(_pip_version "ruff")
codespell=$(_pip_version "codespell")

mkdir -p super-linter-versions

cat >"$OUTPUT" <<EOF
# Tool versions matching super-linter ${TAG}
# Source: https://github.com/${REPO}/tree/${TAG}
#
# Auto-generated by tasks/setup/update-super-linter-versions.sh
# Dockerfile multi-stage builds pin exact versions for compiled tools.
# npm and python versions come from lock files in dependencies/.

[tools]
shellcheck = "${shellcheck}"
shfmt = "${shfmt}"
actionlint = "${actionlint}"
hadolint = "${hadolint}"
"npm:markdownlint-cli" = "${markdownlint}"
"npm:prettier" = "${prettier}"
"npm:@biomejs/biome" = "${biome}"
"pipx:ruff" = "${ruff}"
"pipx:codespell" = "${codespell}"
editorconfig-checker = "${editorconfig_checker}"
golangci-lint = "${golangci_lint}"
EOF

echo "Written to ${OUTPUT}"
echo ""
cat "$OUTPUT"
